2025-09-14 21:54:08,167 : INFO - Attempting to open/read file
2025-09-14 21:55:14,783 : ERROR - Error Type: <class 'OSError'> - [Errno 22] Invalid argument: 'C:\\Users\\istevens\\source\repos\\PYTHON SCRIPTS\\PythonFileManagement\\transactions\\data\\temp\\CLAIMASSESSMENT.T40J003.20250913.txt'
Traceback (most recent call last):
  File "C:\Users\istevens\source\repos\PYTHON SCRIPTS\PythonFileManagement\BusinessJobs\Assessment_T40.py", line 94, in GetMedicalCareReceivedTapes
    with open("C:\Users\istevens\source\repos\PYTHON SCRIPTS\PythonFileManagement\transactions\data\temp\CLAIMASSESSMENT.T40J003.20250913.txt", "r", encoding="utf-8", errors="ignore") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'C:\\Users\\istevens\\source\repos\\PYTHON SCRIPTS\\PythonFileManagement\\transactions\\data\\temp\\CLAIMASSESSMENT.T40J003.20250913.txt'
